### ISSUE TITLE
如何解决 umd 包下 namedExports 的问题？

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/father#168]
转一个 bug ，怕被遗忘了。
原始 bug 在 [DragAndDrop/issues](https://github.com/alitajs/DragAndDrop/issues/1)
重现demo [DragAndDrop](https://github.com/alitajs/DragAndDrop)
`yarn && yarn run build`

```bash
Build umd
'domain' is imported by node_modules/asap/raw.js, but could not be resolved – treating it as an external dependency
'domain' is imported by domain?commonjs-external, but could not be resolved – treating it as an external dependency
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragSource.js -> node_modules/react-dnd/dist/esm/decorators/decorateHandler.js -> node_modules/react-dnd/dist/esm/index.js
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragLayer.js -> node_modules/react-dnd/dist/esm/index.js
'createContext' is not exported by 'node_modules/react/index.js'
✖  error     Error: 'memo' is not exported by node_modules/react/index.js 
    at error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:9365:30)
    at Module.error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13271:9)
    at handleMissingExport (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13194:21)
    at Module.traceVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13573:17)
    at ModuleScope.findVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:12293:39)
    at Identifier$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:8313:40)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7949:23)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:10300:15)
    at VariableDeclarator.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7949:23)
    at VariableDeclaration$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7945:31)
error Command failed with exit code 1.
```

**Comment by ycjcl868** [comment]
参考写法：

```js
const findPath = (moduleName) => {
  const pathArr = require.resolve(moduleName).split('/');
  const pathIndex = pathArr.findIndex(path => path === 'packages');
  const path = `${pathArr.slice(pathIndex).join('/')}`
  return path;
}

export default {
  namedExports: {
    // tnpm 会给包名加上版本号，所以直接写包名会找不到，需要手动寻找包的详细路径
    [`${findPath('react-is')}`]: [
      'isFragment',
      'isElement',
      'isValidElementType',
      'ForwardRef',
    ],
    [`${findPath('lodash')}`]: [
      'debounce',
      'isArray',
      'get',
      'set'
    ],
  }
}

```

**Comment by xiaohuoni** [comment]
没解决。

**Comment by rdmclin2** [comment]
真是坑呀，昨天搞了半天没解决，写成了` import times from 'lodash/times'` 的形式

**Comment by xiaohuoni** [comment]
@sorrycc

**Comment by xiaohuoni** [comment]
引入的包需要在 `peerDependencies` 或者 `dependencies` 中
```
  "peerDependencies": {
    "react": "^16.8.5"
  },
```
