### ISSUE TITLE
不能导入less文件

### ISSUE THREAD

**Issue by lei3536** [umijs/father#247]
## What happens?
样式文件
```less
.primary-color {
  color: red;
}

```
js文件
```js
import React from 'react';
import styles from './style.less';

interface TagsCloudProps {}
const TagsCloud: React.FC<TagsCloudProps> = ({}) => {
  // return <div className="primary-color">嘿嘿黑</div>;
  return <div className={styles['primary-color']}>嘿嘿黑</div>;
};
export default TagsCloud;
```
配置文件
```
esm: { type: 'babel', importLibToEs: true },
  umd: {
    file: 'index',
    sourcemap: false,
  },
  extraBabelPlugins: [['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]],
  extraExternals: ['react', 'react-dom', 'prop-types'],
```

## 复现步骤，错误日志以及相关配置
yarn start 后 报错
```
ERROR in ./src/components/TagsCloud/style.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ref--10-2!./src/components/TagsCloud/style.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'javascriptEnabled'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap?, implementation? }
    at validate (/Users/elelee/Desktop/projects/my-comp-lib/node_modules/less-loader/node_modules/schema-utils/dist/validate.js:96:11)
    at Object.lessLoader (/Users/elelee/Desktop/projects/my-comp-lib/node_modules/less-loader/dist/index.js:24:28)
```
![image](https://user-images.githubusercontent.com/29876945/91841265-a23d8380-ec84-11ea-8157-da76a7e560d5.png)

## 相关环境信息

- **Father 版本**：
2.29.8
- **Node 版本**：
v12.16.1
- **antd版本**：
4.5.4

**Comment by PeachScript** [comment]
目前 father 内置的 storybook 及配置较陈旧，建议使用 dumi + father-build 做组件库开发：https://d.umijs.org/guide/getting-started#%E7%BB%84%E4%BB%B6%E5%BC%80%E5%8F%91%E8%84%9A%E6%89%8B%E6%9E%B6

**Comment by lei3536** [comment]
@PeachScript 已经改了，还有有这个问题。后来发现是另外有一个依赖影响了这个打包，ant-tools里面的gulp-less
