### ISSUE TITLE
组件打包报错：error     Error: 'isFragment' is not exported by ../../../node_modules/react-is/index.js 

### ISSUE THREAD

**Issue by greenPeppers** [umijs/father#278]
Clean dist directory
Build esm with rollup
rpt2: You are using 'objectHashIgnoreUnknownHack' option. If you enabled it because of async functions, try disabling it now.
✖  error     Error: 'isFragment' is not exported by ../../../node_modules/react-is/index.js 
    at error (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:5363:30)
    at Module.error (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:9701:9)
    at handleMissingExport (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:9618:21)
    at Module.traceVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:10009:17)
    at ModuleScope.findVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:8678:39)
    at FunctionScope.findVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:3054:38)
    at ChildScope.findVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:3054:38)
    at FunctionScope.findVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:3054:38)
    at ChildScope.findVariable (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:3054:38)
    at Identifier$1.bind (/Users/chashugu/Desktop/work/project/library/node_modules/rollup/dist/rollup.js:4392:40)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
Circular dependency: ../../../node_modules/antd/es/empty/index.js -> ../../../node_modules/antd/es/config-provider/index.js -> ../../../node_modules/antd/es/config-provider/context.js -> ../../../node_modules/antd/es/config-provider/renderEmpty.js -> ../../../node_modules/antd/es/empty/index.js
Circular dependency: ../../../node_modules/antd/es/config-provider/index.js -> ../../../node_modules/antd/es/config-provider/context.js -> ../../../node_modules/antd/es/config-provider/renderEmpty.js -> ../../../node_modules/antd/es/config-provider/index.js
Circular dependency: ../../../node_modules/antd/es/config-provider/index.js -> ../../../node_modules/antd/es/message/index.js -> ../../../node_modules/antd/es/message/hooks/useMessage.js -> ../../../node_modules/antd/es/config-provider/index.js
Circular dependency: ../../../node_modules/antd/es/message/index.js -> ../../../node_modules/antd/es/message/hooks/useMessage.js -> ../../../node_modules/antd/es/message/index.js
Circular dependency: ../../../node_modules/antd/es/config-provider/index.js -> ../../../node_modules/antd/es/notification/index.js -> ../../../node_modules/antd/es/notification/hooks/useNotification.js -> ../../../node_modules/antd/es/config-provider/index.js
error Command failed with exit code 1.

**Comment by PeachScript** [comment]
react 写进 `dependencies`

**Comment by yandeqiang** [comment]
这是因为 commonjs 的原因吗？ 如果有其他 commonjs 的包， 有通用解法吗？
