### ISSUE TITLE
bug: 使用 babel 模式构建报错

### ISSUE THREAD

**Issue by jianfei** [umijs/father#285]
在使用 dumi 时发现的，猜测应该是 `father-build` 模块的问题

### Versions

- dumi: 1.0.37
- node: 12.18.3
- npm: 6.14.8
- OS: Windows
- Browser: -

### Steps to reproduce

1. 随便新建一个文件夹
2. 使用 `yarn create @umijs/dumi-lib` 初始化项目
3. 执行 `yarn` 安装依赖
4. 只需要将 `.fatherrc.ts` 中的两个 `rollup` 改成 `babel`
5. 执行 `yarn build` 进行构建

结果：大量报错

```
D:/projects/dumi-test/node_modules/@types/react-router/node_modules/@types/react/index.d.ts(2981,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
D:/projects/dumi-test/node_modules/@types/react-router/node_modules/@types/react/index.d.ts(2992,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
D:/projects/dumi-test/node_modules/@types/react-router/node_modules/@types/react/index.d.ts(2993,13): error TS2717: Subsequent property declarations must have the same type.  Property 'abbr' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.

.... 中间信息几乎都是差不多的，由于太长省略掉了....

D:/projects/dumi-test/node_modules/@types/react/index.d.ts(2982,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
D:/projects/dumi-test/node_modules/@types/vfile/index.d.ts(11,31): error TS7016: Could not find a declaration file for module 'vfile-message'. 'D:/projects/dumi-test/node_modules/vfile-message/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vfile-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'vfile-message';`
Transform to cjs for D:/projects/dumi-test/src/index.js
Transform to cjs for D:/projects/dumi-test/src/Foo/index.js
TypeScript: 178 semantic errors
TypeScript: emit succeeded (with errors)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (D:\projects\dumi-test\node_modules\gulp-typescript\release\output.js:130:43)
    at D:\projects\dumi-test\node_modules\gulp-typescript\release\output.js:43:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (D:\projects\dumi-test\node_modules\duplexify\index.js:191:15)
    at D:\projects\dumi-test\node_modules\duplexify\index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is Expected?

应该能够正常构建

**Comment by PeachScript** [comment]
Duplicate with https://github.com/umijs/dumi/issues/407 , closed

**Comment by cbbfcd** [comment]
问题 +1
