### ISSUE TITLE
请问打包如何支持可选链

### ISSUE THREAD

**Issue by quicklearning123** [umijs/father#315]
npm run build 报错， 但npm run start 可以看到demo效果

![image](https://user-images.githubusercontent.com/70048681/108590801-64522a00-73a0-11eb-9a31-44a9d38b8224.png)
```
 fath npm run build

> fath@1.0.0 build /Users/xxx/dev/fath
> father-build

Clean dist directory
Build cjs with rollup
✖  error     Error: /Users/xxx/dev/fath/src/SystemManage/Setting/index.tsx(100,28): syntax error TS1109: Expression expected.
    at error (/Users/xxx/dev/fath/node_modules/rollup/dist/shared/rollup.js:5253:30)
    at throwPluginError (/Users/xxx/dev/fath/node_modules/rollup/dist/shared/rollup.js:17926:12)
    at Object.error (/Users/xxx/dev/fath/node_modules/rollup/dist/shared/rollup.js:18533:24)
    at Object.error (/Users/xxx/dev/fath/node_modules/rollup/dist/shared/rollup.js:18095:38)
    at RollupContext.error (/Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at Function._.each [as forEach] (/Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9368:14)
    at printDiagnostics (/Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/Users/xxx/dev/fath/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fath@1.0.0 build: `father-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fath@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-02-20T09_43_17_925Z-debug.log
```

工程是dumi生成的
配置如下：
```
export default {
  esm: 'rollup',
  cjs: 'rollup',
};

```
package.json
```
{
  "private": true,
  "name": "fath",
  "version": "1.0.0",
  "scripts": {
    "start": "dumi dev",
    "docs:build": "dumi build",
    "docs:deploy": "gh-pages -d docs-dist",
    "build": "father-build",
    "deploy": "npm run docs:build && npm run docs:deploy",
    "release": "npm run build && npm publish",
    "prettier": "prettier --write \"**/*.{js,jsx,tsx,ts,less,md,json}\"",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "main": "dist/index.js",
  "module": "dist/index.esm.js",
  "typings": "dist/index.d.ts",
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@ant-design/pro-layout": "6.5.14",
    "@ant-design/pro-table": "^2.8.1",
    "antd": "^4.6.5",
    "father": "^2.30.1",
    "js-cookie": "^2.2.1",
    "react": "^16.12.0",
    "umi": "^3.2.21",
    "umi-request": "^1.0.8"
  },
  "devDependencies": {
    "@umijs/fabric": "^2.2.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.0-beta.2",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.7.0",
    "@umijs/preset-ui": "^2.0.9",
    "@umijs/yorkie": "^2.0.3",
    "dumi": "^1.0.13",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  }
}

```
请教下我需要怎么配置呢？
我这个工程的目的是，把用户/权限/部门管理页面打成一个私有npm包，给各项目引用。所以里面有umi的request等一些依赖库。
如果有其他更好的方案，可以指导一下吗

**Comment by PeachScript** [comment]
试了下无法复现，检查下是否改动了 tsconfig.json 里的 target
