### ISSUE TITLE
组件内引用静态资源，运行 npm run build 报错

### ISSUE THREAD

**Issue by TwoOld** [umijs/father#389]
使用 npx @umijs/create-dumi-lib 生成项目，将打包模式改为 babel

配置 extraBabelPlugins

```
extraBabelPlugins:[
    [
      "file-loader",
      {
        "name": "[hash].[ext]",
        "extensions": ["png", "jpg", "jpeg", "gif", "svg"],
        "publicPath": "/public",
        "outputPath": "/public",
        "context": "",
        "limit": 0
      }
    ]
  ]
```

运行 npm run build 失败

```shell
> test-file@1.0.0 build /Users/seventh/Documents/workspace/test-file
> father-build

Clean dist directory
Build cjs with babel
Clean lib directory
src/Foo/index.tsx(2,19): error TS2307: Cannot find module './empty.svg' or its corresponding type declarations.
Transform to cjs for src/index.js
Transform to cjs for src/Foo/index.js
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/Users/seventh/Documents/workspace/test-file/node_modules/gulp-typescript/release/output.js:130:43)
    at /Users/seventh/Documents/workspace/test-file/node_modules/gulp-typescript/release/output.js:43:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Duplexify instance at:
    at Duplexify._destroy (/Users/seventh/Documents/workspace/test-file/node_modules/duplexify/index.js:191:15)
    at /Users/seventh/Documents/workspace/test-file/node_modules/duplexify/index.js:182:10
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

复现地址：[https://github.com/TwoOld/father-build-file](https://github.com/TwoOld/father-build-file)

**Comment by TwoOld** [comment]
解决方法：https://github.com/umijs/father/issues/227#issuecomment-720928000
