### ISSUE TITLE
Babel 官方发布新版本 7.16.0 后，father build 无法使用

### ISSUE THREAD

**Issue by jianfei** [umijs/father#418]
我这边所有使用 father 打包的项目都报以下错误：
```
✖  error     TypeError: /Users/zl/Projects/web-ui/src/components/table/index.tsx: Cannot read properties of undefined (reading 'path')
    at PluginPass.enter (/Users/zl/Projects/web-ui/node_modules/father-build/node_modules/@babel/plugin-transform-typescript/lib/index.js:242:52)
    at newFn (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/context.js:131:19)
    at Function.traverse.node (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/index.js:82:17)
    at traverse (/Users/zl/Projects/web-ui/node_modules/@babel/traverse/lib/index.js:62:12)
error Command failed with exit code 1.
```

**Comment by dino-zhao** [comment]
我也遇到了

**Comment by PeachScript** [comment]
已经给 babel 提交 PR 了：https://github.com/babel/babel/pull/13900

father 是锁了顶层依赖的，但锁不了下层，遇到问题可以先项目 `package.json` 里用 `resolutions` 解一下：https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by daiyang123456** [comment]
> 已经给 babel 提交 PR 了：[babel/babel#13900](https://github.com/babel/babel/pull/13900)
> 
> father 是锁了顶层依赖的，但锁不了下层，遇到问题可以先项目 `package.json` 里用 `resolutions` 把 `@babel/plugin-transform-typescript` 锁到 `7.15.8` 解一下：https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

似乎这个方案不行，还是一样的报错

**Comment by PeachScript** [comment]
可以直接重装依赖了，babel 已经发布了修复版：https://github.com/babel/babel/releases/tag/v7.16.1

issue 关闭，有问题再反馈

**Comment by chenyulun** [comment]
@PeachScript 
帮忙看一下
<img width="774" alt="image" src="https://user-images.githubusercontent.com/15979948/153840790-e1077288-2b44-4714-82b2-9ffe6338d177.png">
