### ISSUE TITLE
father-build 打包报错

### ISSUE THREAD

**Issue by hotoo** [umijs/father#427]
@sorrycc 

```bash
> @ build /home/jenkins/agent/aci
> father build

@alipay/tango: Clean dist directory
@alipay/tango: Build cjs with babel
@alipay/tango: Clean lib directory
error TS5023: Unknown compiler option 'cwd'.
/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/lib/index.js:21
    return IMPORT_PATTERNS.flatMap((pattern) => [...line.matchAll(pattern)].map((match) => match[2]));
                                                         ^

TypeError: line.matchAll(...) is not a function or its return value is not iterable
    at IMPORT_PATTERNS.flatMap (/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/src/index.ts:39:56)
    at flattenIntoArray (/home/jenkins/agent/aci/node_modules/_prettier@2.4.1@prettier/doc.js:1088:27)
    at Array.flatMap (/home/jenkins/agent/aci/node_modules/_prettier@2.4.1@prettier/doc.js:1138:18)
    at findImports (/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/src/index.ts:39:26)
    at file.flatMap (/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/src/index.ts:32:5)
    at flattenIntoArray (/home/jenkins/agent/aci/node_modules/_prettier@2.4.1@prettier/doc.js:1088:27)
    at Array.flatMap (/home/jenkins/agent/aci/node_modules/_prettier@2.4.1@prettier/doc.js:1138:18)
    at parseImports (/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/src/index.ts:31:15)
    at Transform.transform [as _transform] (/home/jenkins/agent/aci/node_modules/_@gulp-plugin_alias@2.2.2@@gulp-plugin/alias/src/index.ts:165:23)
    at Transform._read (_stream_transform.js:190:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `father build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.tnpm_tmp/tnpm.2021-11-11.400.1636579935154/_logs/2021-11-10T21_34_09_155Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ci: `lerna bootstrap && npm run lint && npm run build && npm run cov`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.tnpm_tmp/tnpm.2021-11-11.400.1636579935154/_logs/2021-11-10T21_34_09_184Z-debug.log
[tnpm] subprocess:/root/.cli/.packages/tnpm/lib/npm_child_process.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] archiveArtifacts
Archiving artifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // ws
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by mctl** [comment]
试试回滚版本吧，我这边1.20.1没问题

**Comment by PeachScript** [comment]
确保 Node.js 版本 12+

**Comment by PeachScript** [comment]
已暂时回退 `father` 和 `father-build` 两个包的 latest tag，新引入的依赖是为了解 babel 模式下的 alias 场景 #423 

@ldwonday 看看兼容性问题怎么解？

**Comment by PeachScript** [comment]
@hotoo @mctl 当前安装的 Node.js 版本是多少

**Comment by jefferyssy** [comment]
tsconfig 相对应的是声明功能 现在father-build去读取 path 声明路径，不太合适吧。 不能用于 别名场景#423吧

**Comment by hotoo** [comment]
Node 10，以及升级 Node 解决了。

**Comment by jefferyssy** [comment]
比如现在 lerna 多包模式下。 

比如有个包 demo 的npm包
代码中使用 import * from demo;

但是开发环境中，我暂时不用引用线上包 
比如 在主项目src下，有些开发demo资源， 我通过tsconfig的 path 声明到 src 目录下
在.fatherrc.ts 中，我不需要取修改路径。
现在 去读取tsconfig的path做babel。 破坏了 tsconfig.json 的声明功能了

我在全局tsconfig中设置path 定位一些开发资源，如 path：{ "Root" : "src/" }
打包以后变成 ../../src/

**Comment by hotoo** [comment]
@jefferyssy 你自己另起 issue 讨论吧。

**Comment by ldwonday** [comment]
这个插件官方是不是可以和extraBabelPlugins参数一样，让使用者自己传入gulp插件去介入ts编译的过程呢？

**Comment by mctl** [comment]
> @hotoo @mctl 当前安装的 Node.js 版本是多少

我这本地打包没问题，服务器node是v10.15.3，所以...
