### ISSUE TITLE
ts 编译报错

### ISSUE THREAD

**Issue by daqi** [umijs/father#67]
```
ℹ  info      [smr] Clean dist directory
ℹ  info      [smr] Build esm with undefined
✖  error     Error: failed to open 'undefined' 
    at parseTsConfig (/work/smr/node_modules/rollup-plugin-typescript2/src/parse-tsconfig.ts:17:9)
    at Object.options (/work/smr/node_modules/rollup-plugin-typescript2/src/index.ts:80:64)
    at applyOptionHook (/work/smr/node_modules/rollup/dist/rollup.js:17127:31)
    at Array.reduce (<anonymous>)
    at getInputOptions$1 (/work/smr/node_modules/rollup/dist/rollup.js:17145:41)
    at rollup (/work/smr/node_modules/rollup/dist/rollup.js:17189:30)
    at /work/smr/node_modules/father-build/lib/rollup.js:70:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/work/smr/node_modules/father-build/lib/rollup.js:26:103)
    at _next (/work/smr/node_modules/father-build/lib/rollup.js:28:194)
```

**Comment by sorrycc** [comment]
给复现步骤，原因应该是没找到 `tsconfig.json`。

**Comment by daqi** [comment]
babel可以编译， rollup报错

我用了lerna，是不是每个package都需要tsconfig.json文件

**Comment by sorrycc** [comment]
是的。
