### ISSUE TITLE
package 设置 exports 字段时，umd 构建失败

### ISSUE THREAD

**Issue by Wxh16144** [umijs/father#692]
**复现仓库：** https://github.com/Wxh16144/father-bug-report

**问题描述：** 仓库 readme.md

<details><summary>build logs</summary>
<p>

> bar@1.0.0 build /Users/wuxh/Code/father-bug-report/packages/bar
> father build

info  - Clean output directories
info  - Bundle from src/utils/index.ts to dist/index.min.js
error - Error: ERROR in ./src/utils/index.ts 1:0-32
Module not found: Error: Can't resolve 'foo/utils' in '/Users/wuxh/Code/father-bug-report/packages/bar/src/utils'

webpack compiled with 1 error
    at handler (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/dist/build.js:82:79)
    at finalCallback (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61937:32)
    at /Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61954:13
    at Hook.eval [as callAsync] (eval at create (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4913)
    at onCompiled (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:61952:21)
    at /Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62692:17
    at Hook.eval [as callAsync] (eval at create (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4913)
    at /Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62688:33
    at finalCallback (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:58974:11)
    at /Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:59279:11
    at Hook.eval [as callAsync] (eval at create (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4913)
    at /Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-webpack@4.0.74_styled-components@6.0.7_typescript@5.0.4_webpack@5.88.2/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:59272:38
    at eval (eval at create (/Users/wuxh/Code/father-bug-report/node_modules/.pnpm/@umijs+bundler-utils@4.0.74/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7744), <anonymous>:17:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.

</p>
</details>

**Comment by Wxh16144** [comment]
开发任务有点忙，不太确定是否是我配置问题还是 father 存在 bug， 没有深入 debug
